### ISSUE TITLE
stack can build docker images

### ISSUE THREAD

**Issue by ketzacoatl** [naushadh/hello-world#3]
Awesome project! You may already know this, so feel free to ignore me if so. In case this is news, I thought you might find it helpful to know that `stack` can build docker images for you, and it's quite nice. For example:

```
image:
  containers:
  - name: foobar
    base: alpine:latest
```
